menu:
    Blog: /
    Archive: /archives/
    GitHub: /
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
livere:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
copyright: Published with ❤️
startyear: 2015
